<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>WorkTimeChat.Vk</AssemblyName>
        <RootNamespace>WorkTimeChat.Vk</RootNamespace>
        <PackageId>WorkTimeChat.Vk</PackageId>
        <Authors>WorkTimeChat.Vk</Authors>
        <Company>WorkTimeChat.Vk</Company>
        <Product>WorkTimeChat.Vk</Product>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="TelegramBotBase" Version="7.0.0" />
      <PackageReference Include="VkNet" Version="1.78.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WorkTimeChat.Forms\WorkTimeChat.Forms.csproj" />
    </ItemGroup>

</Project>
